### ISSUE TITLE
MQTT to postgresql

### ISSUE THREAD

**Issue by jancelin** [TamataOcean/OceanIsOpen#1]
Note pour plus tard @RomainTourte 

https://github.com/chuanjin/docker-mosquitto-postgres

https://github.com/chuanjin/docker-mosquitto-postgres/blob/master/Dockerfile-mosquitto

https://github.com/chuanjin/docker-mosquitto-postgres/blob/master/mqtt.conf

**Comment by RomainTourte** [comment]
le script save_data.js peut faire appel à la librairie postgres pour écrire directement dans la base ;)

https://node-postgres.com/

**Comment by RomainTourte** [comment]
Une piste pour les tables de PostGIS combinant position GPS & data des capteurs... https://gis.stackexchange.com/questions/225523/storing-gps-and-mobile-sensor-data

**Comment by RomainTourte** [comment]
@jancelin le service save_data.js prend maintenant en charge l'écriture dans la base Postgres. A la réception d'un message typé JSON dans mosquitto, on écrit dans la table "sensors" de postgres ;)
![MqttToPostgres](https://user-images.githubusercontent.com/25310798/65668261-abb87780-e041-11e9-902c-55688c4e5417.jpg)
